---
mock_with: ':rspec'
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 95
Rakefile:
  changelog_user: adobe
  extra_disabled_lint_checks:
    - '140chars'
  extras:
    - 'task :headers do'
    - "  require 'copyright_header' if Bundler.rubygems.find_name('copyright-header')"
    - '  args = {'
    - "    :license => 'ASL2',"
    - "    :copyright_software => 'Puppet Dispatcher Module',"
    - '    :copyright_software_description => "A module to manage AEM Dispatcher installations and configuration files.",'
    - "    :copyright_holders => ['Adobe Inc'],"
    - "    :copyright_years => ['2019'],"
    - "    :add_path => 'manifests:types:files:templates:spec',"
    - "    :output_dir => '.',"
    - "    :syntax => 'config/syntax.yml',"
    - '    :word_wrap => 200'
    - '  }'
    - '  command_line = CopyrightHeader::CommandLine.new( args )'
    - '  command_line.execute'
    - 'end'

Gemfile:
  required:
    ':development':
      - gem: copyright-header
        version: '~>1.0'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '>=1.15'

.rubocop.yml:
  default_configs:
    AllCops:
      TargetRubyVersion: '2.4'
    Style/WordArray:
      EnforcedStyle: percent
    Layout/EmptyLinesAroundBlockBody:
      Enabled: false

.travis.yml:
  dist: xenial
  deploy_to_forge:
    enabled: true
    tag_regex: '^v\d'
  user: adobeinc
  secure: "hTj2dy3z0h26hzY3XdJop0IMac8DYu/z949XRTpo/pkVn/dSMnGbREFkyBO99dicdRlQAwbO7VFZTCfKUrDxA3p/+ECh7mjwPcYwM8oTryarGpcmXso7vROkdxzObOHUZn33A5fKzYZqbgh54zI3ngwFkQKTyyDgMU+7RolsO3dBbhV6jEstF4a4V2DCJrPIDMS3nuLzhRP6dn82P8lrOaunW/Gg8j5STNPiv305hgzP9n2UZb+h1P47aOsS60/Lc1nbxCN5PyymKHGDrMPX6RpsE9PpvWNtnr4rViINdeP5V5H+g7UKxWypVn2msKw+slW2RFYekaRum74fQDpF7IOzh8FLwWNPvJK7GYXxkzVul2VnJw7xSQHTkhfTXcwsBn+lrwY7wkjmW9GP6gv+BlTiMXQTWQR+6AK41MXDjR9fj7cqUK/K+bgnPw1Q0SdPoX0c+5blhbKT6rDeYMv8KBH4H/b7scuF+XBMaj0hxUA3ErZBk63KhjABFz/YfTG3/b5HDeOggpolpn5NsOrhOTV0EPXuaPfles7H2c9Vd1A7GDh2OyuSaiu7Z9Vk2t27HQzQ2m2JEQJ1XsM+dYrHCYNBP6WcLUe4pfYGex2HHHohmn8I81Ag3JVvub1ScsloScUK0qjHiKEVy9cilcTQ7AGx0BgMwM03W3rho1nSIAo="
  includes:
  - bundler_args:
    dist: xenial
    env: PLATFORMS=debian_puppet5
    rvm: 2.5.1
    before_script:
      - bundle exec rake 'litmus:provision_list[debian]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
    script:
      - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args:
    dist: xenial
    env: PLATFORMS=debian_puppet6
    rvm: 2.5.1
    before_script:
      - bundle exec rake 'litmus:provision_list[debian]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
    script:
      - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args:
    dist: xenial
    env: PLATFORMS=ubuntu_puppet5
    rvm: 2.5.1
    before_script:
      - bundle exec rake 'litmus:provision_list[ubuntu]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
    script:
      - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args:
    dist: xenial
    env: PLATFORMS=ubuntu_puppet6
    rvm: 2.5.1
    before_script:
      - bundle exec rake 'litmus:provision_list[ubuntu]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
    script:
      - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args:
    dist: xenial
    env: PLATFORMS=el_puppet5
    rvm: 2.5.1
    before_script:
      - bundle exec rake 'litmus:provision_list[el]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
    script:
      - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args:
    dist: xenial
    env: PLATFORMS=el_puppet6
    rvm: 2.5.1
    before_script:
      - bundle exec rake 'litmus:provision_list[el]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
    script:
      - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
