---
mock_with: ':rspec'
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 95
Rakefile:
  extra_disabled_lint_checks:
    - '140chars'

.rubocop.yml:
  default_configs:
    AllCops:
      TargetRubyVersion: '2.4'
    Style/WordArray:
      EnforcedStyle: percent
    Layout/EmptyLinesAroundBlockBody:
      Enabled: false
